//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstructorCourseSim
    {
        public int EmployeeID { get; set; }
        public int courseID { get; set; }
        public int platformID { get; set; }
        public int ProgramIntkeID { get; set; }
        public int row_id { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Platform Platform { get; set; }
        public virtual ProgramIntake ProgramIntake { get; set; }
    }
}
